CREATE TABLE `operational_module_records` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `moduleSlug` VARCHAR(80) NOT NULL,
  `moduleTitle` VARCHAR(150) NOT NULL,
  `recordNumber` VARCHAR(80) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `workflowStage` VARCHAR(100) NOT NULL,
  `statusCode` VARCHAR(50) NOT NULL DEFAULT 'OPEN',
  `priorityCode` VARCHAR(50) NOT NULL DEFAULT 'ROUTINE',
  `facilityId` INTEGER NOT NULL,
  `branchId` INTEGER NULL,
  `patientId` INTEGER NULL,
  `assignedStaffId` INTEGER NULL,
  `createdByUserId` INTEGER NULL,
  `dueAt` DATETIME(3) NULL,
  `startedAt` DATETIME(3) NULL,
  `completedAt` DATETIME(3) NULL,
  `closedAt` DATETIME(3) NULL,
  `metadata` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `operational_module_records_recordNumber_key`(`recordNumber`),
  INDEX `operational_module_records_facilityId_idx`(`facilityId`),
  INDEX `operational_module_records_branchId_idx`(`branchId`),
  INDEX `operational_module_records_moduleSlug_idx`(`moduleSlug`),
  INDEX `operational_module_records_statusCode_idx`(`statusCode`),
  INDEX `operational_module_records_priorityCode_idx`(`priorityCode`),
  INDEX `operational_module_records_createdAt_idx`(`createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
